Android 11 open camera fix
OutSystems/cordova-plugin-camera pull request #12
Opened 2020-12-03 21:42 UTC by andregrillo

## Description

Merge branch **fix/RMET-376/camera-update-for-android-11-MABS7** into OutSystems branch and keep the custom changes made by OutSystems
## Context

Closes the issue: https://outsystemsrd.atlassian.net/browse/RMET-376

Change required to fix camera access in Android 11
 
## Type of changes

- [ ] Feature (change which adds functionality)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to new feature)
- [x] Fix (change which fixes an issue)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to fix)
- [ ] Performance (change which improves performance)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to performance improvement)
- [ ] Refactor (non-breaking change that is neither feature, fix nor performance)
- [ ] Style (non-breaking change that only affects formatting and/or white-space)

## Components affected
- [x] Android platform
- [ ] iOS platform
- [ ] JavaScript
- [ ] OutSystems

## Tests

Tested with Camera Sample App in saucelab devices

## Screenshots (if appropriate)

## Checklist

- [x] Pull request title follows the format `RNMT-XXXX <title>`
- [ ] Tests have been created
- [x] Code follows the code style of this project
- [ ] CHANGELOG.md file is correctly updated
- [ ] Changes require an update to the documentation
	- [ ] Documentation has been updated accordingly

2020-12-03 22:01 UTC, CarlsCorrea approved these changes

2020-12-03 22:12 UTC, usernuno approved these changes

2020-12-04 08:58 UTC, vmfo22 requested changes

2020-12-04 08:58 UTC, vmfo22 commented on plugin.xml
> +    version="4.2.1-OS">
The version is wrong. You should put 4.2.0-OS2 because we're applying a fix on our side on top of what we get from the upstream. The version itself must correspond to the version from the upstream repo.

2020-12-04 09:30 UTC, andregrillo commented on plugin.xml
> +    version="4.2.1-OS">
Version changed to 4.2.0-OS2 as required.

2020-12-04 09:41 UTC, CarlsCorrea approved these changes

2020-12-04 10:03 UTC, GFOutsystems approved these changes

2020-12-04 10:13 UTC, vmfo22 approved these changes

2020-12-04 12:17 UTC, merged