RMET-2351::: Wrapper ::: Add thumbnail output parameter for RecordVideo
OutSystems/cordova-plugin-camera pull request #70
Opened 2023-03-16 10:39 UTC by hectorjdgdev

### Platforms affected
Android

### Motivation and Context
We need to add a new output parameter to the method used of recording a video. This output parameter will contain the thumbnail of the video, which will be in a binary format.

### Description
Added thumbnail output parameter to the Media Result structure when recording video

### Testing

https://enmobile11-dev.outsystemsenterprise.com/NativeAppBuilder/App?AppKey=f3d180da-a73a-4245-b8b7-234214294809

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

2023-03-16 11:29 UTC, OS-ricardomoreirasilva approved these changes

2023-03-16 11:55 UTC, nflsilva requested changes

2023-03-16 11:55 UTC, nflsilva commented on src/android/CameraLauncher.kt
> +                uri?.let {
maybe I'm being a little picky. But would this look better with a guard?
Something like
```
if (uri == null) {
 sendError(OSCAMRError.CAPTURE_VIDEO_ERROR)
 return
}
camController?.processResultFromVideo( ....
```

2023-03-16 11:55 UTC, nflsilva commented on src/android/CameraLauncher.kt
> +                uri?.let {
I have a problem with multiple nesting 😄

2023-03-16 15:05 UTC, hectorjdgdev commented on src/android/CameraLauncher.kt
> +                uri?.let {
hahahaha okokok, for me is the same result, what works best for you guys in order to understand the code

2023-03-22 10:02 UTC, alexgerardojacinto approved these changes

2023-03-23 17:27 UTC, merged